// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbLOG_Account
    public partial class Account: BaseEntity
    {
        public Guid ID { get; set; } // ID (Primary key)

        ///<summary>
        /// 账号
        ///</summary>
        public string AccountID { get; set; } // AccountID

        ///<summary>
        /// 姓名
        ///</summary>
        public string Name { get; set; } // Name

        ///<summary>
        /// 密码
        ///</summary>
        public string Password { get; set; } // Password

        ///<summary>
        /// 性别
        ///</summary>
        public int Sex { get; set; } // Sex

        ///<summary>
        /// 生日
        ///</summary>
        public DateTime Birthday { get; set; } // Birthday

        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新时间
        ///</summary>
        public DateTime UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 职位
        ///</summary>
        public Guid Position { get; set; } // Position

        ///<summary>
        /// 头像
        ///</summary>
        public string Img { get; set; } // Img

        ///<summary>
        /// 部门
        ///</summary>
        public Guid Department { get; set; } // Department

        ///<summary>
        /// 是否启用
        ///</summary>
        public bool IsUse { get; set; } // IsUse

        ///<summary>
        /// 有效时间
        ///</summary>
        public DateTime ExpireDate { get; set; } // ExpireDate
        
        public Account()
        {
            AccountID = "";
            Name = "";
            Password = "";
            Sex = 0;
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
            Position = Guid.Parse("00000000-0000-0000-0000-000000000000");
            Img = "";
            Department = Guid.Parse("11111111-1111-1111-1111-111111111111");
            IsUse = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
