// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbLOG_AccountOfRole
    public partial class AccountOfRole: BaseEntity
    {
        public Guid ID { get; set; } // ID (Primary key)

        ///<summary>
        /// 用户Id
        ///</summary>
        public Guid AccountID { get; set; } // AccountID

        ///<summary>
        /// 角色Id
        ///</summary>
        public Guid RoleID { get; set; } // RoleID

        ///<summary>
        /// 是否使用
        ///</summary>
        public bool IsUse { get; set; } // IsUse
        
        public AccountOfRole()
        {
            IsUse = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
