// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbCOM_AppVersionControl
    public partial class AppVersionControlConfiguration : EntityTypeConfiguration<AppVersionControl>
    {
        public AppVersionControlConfiguration()
            : this("dbo")
        {
        }
 
        public AppVersionControlConfiguration(string schema)
        {
            ToTable(schema + ".tbCOM_AppVersionControl");
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName("ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Appid).HasColumnName("Appid").IsOptional().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.Version).HasColumnName("Version").IsOptional().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.Note).HasColumnName("Note").IsOptional().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.AndroidUpdateUrl).HasColumnName("AndroidUpdateUrl").IsOptional().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.IosUpdateUrl).HasColumnName("IosUpdateUrl").IsOptional().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.UpdateTime).HasColumnName("UpdateTime").IsOptional().HasColumnType("datetime");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
