// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbLOG_Department
    public partial class Department: BaseEntity
    {

        ///<summary>
        /// 部门ID
        ///</summary>
        public Guid ID { get; set; } // ID (Primary key)

        ///<summary>
        /// 父级ID
        ///</summary>
        public Guid ParentID { get; set; } // ParentID

        ///<summary>
        /// 部门名称
        ///</summary>
        public string Name { get; set; } // Name

        ///<summary>
        /// 类型
        ///</summary>
        public int Type { get; set; } // Type

        ///<summary>
        /// 排序
        ///</summary>
        public int Priority { get; set; } // Priority

        ///<summary>
        /// 是否启用
        ///</summary>
        public bool IsUse { get; set; } // IsUse

        ///<summary>
        /// 域
        ///</summary>
        public short Domain { get; set; } // Domain
        
        public Department()
        {
            ID = System.Guid.NewGuid();
            ParentID = Guid.Parse("00000000-0000-0000-0000-000000000000");
            Name = "";
            Type = 0;
            Priority = 0;
            IsUse = false;
            Domain = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
