// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class FakeMyDbContext : IMyDbContext
    {
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountOfRole> AccountOfRoles { get; set; }
        public DbSet<CodeTable> CodeTables { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<ErrorInfo> ErrorInfoes { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UserLogin> UserLogins { get; set; }
        public DbSet<UserLoginToken> UserLoginTokens { get; set; }
        public DbSet<VersionControl> VersionControls { get; set; }

        public FakeMyDbContext()
        {
            Accounts = new FakeDbSet<Account>("ID");
            AccountOfRoles = new FakeDbSet<AccountOfRole>("ID");
            CodeTables = new FakeDbSet<CodeTable>("ID");
            Departments = new FakeDbSet<Department>("ID");
            ErrorInfoes = new FakeDbSet<ErrorInfo>("ID");
            Logs = new FakeDbSet<Log>("ID");
            Menus = new FakeDbSet<Menu>("ID");
            Permissions = new FakeDbSet<Permission>("ID");
            Roles = new FakeDbSet<Role>("ID");
            UserLogins = new FakeDbSet<UserLogin>("ID");
            UserLoginTokens = new FakeDbSet<UserLoginToken>("ID");
            VersionControls = new FakeDbSet<VersionControl>("Key");

            InitializePartial();
        }
        
        public int SaveChangesCount { get; private set; } 
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        partial void InitializePartial();

        protected virtual void Dispose(bool disposing)
        {
        }
        
        public void Dispose()
        {
            Dispose(true);
        }
        
        // Stored Procedures
    }
}
// </auto-generated>
