// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    public interface IMyDbContext : IDisposable
    {
        DbSet<Account> Accounts { get; set; } // tbLOG_Account
        DbSet<AccountOfRole> AccountOfRoles { get; set; } // tbLOG_AccountOfRole
        DbSet<AppVersionControl> AppVersionControls { get; set; } // tbCOM_AppVersionControl
        DbSet<CodeTable> CodeTables { get; set; } // tbCOM_CodeTable
        DbSet<Department> Departments { get; set; } // tbLOG_Department
        DbSet<Domain> Domains { get; set; } // tbCOM_Domain
        DbSet<ErrorInfo> ErrorInfoes { get; set; } // tbLOG_ErrorInfo
        DbSet<Log> Logs { get; set; } // tbLOG_Log
        DbSet<Menu> Menus { get; set; } // tbLOG_Menu
        DbSet<Permission> Permissions { get; set; } // tbLOG_Permission
        DbSet<Role> Roles { get; set; } // tbLOG_Role
        DbSet<UserLogin> UserLogins { get; set; } // tbLOG_UserLogin
        DbSet<UserLoginToken> UserLoginTokens { get; set; } // tbLOG_UserLoginToken
        DbSet<VersionControl> VersionControls { get; set; } // tbCOM_VersionControl

        int SaveChanges();
        
        // Stored Procedures
    }

}
// </auto-generated>
