// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbLOG_Menu
    public partial class MenuConfiguration : EntityTypeConfiguration<Menu>
    {
        public MenuConfiguration()
            : this("dbo")
        {
        }
 
        public MenuConfiguration(string schema)
        {
            ToTable(schema + ".tbLOG_Menu");
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName("ID").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName("Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.ParentID).HasColumnName("ParentID").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.Url).HasColumnName("Url").IsRequired().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.IsUse).HasColumnName("IsUse").IsRequired().HasColumnType("bit");
            Property(x => x.Priority).HasColumnName("Priority").IsRequired().HasColumnType("int");
            Property(x => x.Icon).HasColumnName("Icon").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.AppTitle).HasColumnName("AppTitle").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
