// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbLOG_Menu
    public partial class Menu: BaseEntity
    {

        ///<summary>
        /// 主键
        ///</summary>
        public Guid ID { get; set; } // ID (Primary key)

        ///<summary>
        /// 菜单名
        ///</summary>
        public string Name { get; set; } // Name

        ///<summary>
        /// 上级Id
        ///</summary>
        public Guid ParentID { get; set; } // ParentID

        ///<summary>
        /// 菜单链接
        ///</summary>
        public string Url { get; set; } // Url

        ///<summary>
        /// 是否使用
        ///</summary>
        public bool IsUse { get; set; } // IsUse

        ///<summary>
        /// 排序
        ///</summary>
        public int Priority { get; set; } // Priority

        ///<summary>
        /// 图标
        ///</summary>
        public string Icon { get; set; } // Icon

        ///<summary>
        /// APP菜单名
        ///</summary>
        public string AppTitle { get; set; } // AppTitle
        
        public Menu()
        {
            Name = "";
            ParentID = Guid.Parse("00000000-0000-0000-0000-000000000000");
            Url = "";
            IsUse = false;
            Priority = 0;
            Icon = "";
            AppTitle = "";
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
