// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    public partial class MyDbContext : DbContext, IMyDbContext
    {
        public DbSet<Account> Accounts { get; set; } // tbLOG_Account
        public DbSet<AccountOfRole> AccountOfRoles { get; set; } // tbLOG_AccountOfRole
        public DbSet<CodeTable> CodeTables { get; set; } // tbCOM_CodeTable
        public DbSet<Department> Departments { get; set; } // tbLOG_Department
        public DbSet<ErrorInfo> ErrorInfoes { get; set; } // tbLOG_ErrorInfo
        public DbSet<Log> Logs { get; set; } // tbLOG_Log
        public DbSet<Menu> Menus { get; set; } // tbLOG_Menu
        public DbSet<Permission> Permissions { get; set; } // tbLOG_Permission
        public DbSet<Role> Roles { get; set; } // tbLOG_Role
        public DbSet<UserLogin> UserLogins { get; set; } // tbLOG_UserLogin
        public DbSet<UserLoginToken> UserLoginTokens { get; set; } // tbLOG_UserLoginToken
        public DbSet<VersionControl> VersionControls { get; set; } // tbCOM_VersionControl
        
        static MyDbContext()
        {
            System.Data.Entity.Database.SetInitializer<MyDbContext>(null);
        }

        public MyDbContext()
            : base("Name=MyDbContext")
        {
            InitializePartial();
        }

        public MyDbContext(string connectionString) : base(connectionString)
        {
            InitializePartial();
        }

        public MyDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model) : base(connectionString, model)
        {
            InitializePartial();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new AccountConfiguration());
            modelBuilder.Configurations.Add(new AccountOfRoleConfiguration());
            modelBuilder.Configurations.Add(new CodeTableConfiguration());
            modelBuilder.Configurations.Add(new DepartmentConfiguration());
            modelBuilder.Configurations.Add(new ErrorInfoConfiguration());
            modelBuilder.Configurations.Add(new LogConfiguration());
            modelBuilder.Configurations.Add(new MenuConfiguration());
            modelBuilder.Configurations.Add(new PermissionConfiguration());
            modelBuilder.Configurations.Add(new RoleConfiguration());
            modelBuilder.Configurations.Add(new UserLoginConfiguration());
            modelBuilder.Configurations.Add(new UserLoginTokenConfiguration());
            modelBuilder.Configurations.Add(new VersionControlConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        public static DbModelBuilder CreateModel(DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new AccountConfiguration(schema));
            modelBuilder.Configurations.Add(new AccountOfRoleConfiguration(schema));
            modelBuilder.Configurations.Add(new CodeTableConfiguration(schema));
            modelBuilder.Configurations.Add(new DepartmentConfiguration(schema));
            modelBuilder.Configurations.Add(new ErrorInfoConfiguration(schema));
            modelBuilder.Configurations.Add(new LogConfiguration(schema));
            modelBuilder.Configurations.Add(new MenuConfiguration(schema));
            modelBuilder.Configurations.Add(new PermissionConfiguration(schema));
            modelBuilder.Configurations.Add(new RoleConfiguration(schema));
            modelBuilder.Configurations.Add(new UserLoginConfiguration(schema));
            modelBuilder.Configurations.Add(new UserLoginTokenConfiguration(schema));
            modelBuilder.Configurations.Add(new VersionControlConfiguration(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void OnModelCreatingPartial(DbModelBuilder modelBuilder);
        
        // Stored Procedures
    }
}
// </auto-generated>
