// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbLOG_Permission
    public partial class Permission: BaseEntity
    {

        ///<summary>
        /// 主键
        ///</summary>
        public Guid ID { get; set; } // ID (Primary key)

        ///<summary>
        /// 菜单Id
        ///</summary>
        public Guid MenuID { get; set; } // MenuID

        ///<summary>
        /// 角色Id
        ///</summary>
        public Guid RoleID { get; set; } // RoleID

        ///<summary>
        /// 部门ID
        ///</summary>
        public Guid DepartmentID { get; set; } // DepartmentID
        
        public Permission()
        {
            DepartmentID = Guid.Parse("00000000-0000-0000-0000-000000000000");
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
