// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Temp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Temp.Data.Entity
{
    // tbLOG_Permission
    public partial class PermissionConfiguration : EntityTypeConfiguration<Permission>
    {
        public PermissionConfiguration()
            : this("dbo")
        {
        }
 
        public PermissionConfiguration(string schema)
        {
            ToTable(schema + ".tbLOG_Permission");
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName("ID").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.MenuID).HasColumnName("MenuID").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.RoleID).HasColumnName("RoleID").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.DepartmentID).HasColumnName("DepartmentID").IsRequired().HasColumnType("uniqueidentifier");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
